### ISSUE TITLE
🐛 : bug Cannot start Gaia "runner" with docker-compose

### ISSUE THREAD

**Issue by tk-subgenius** [gaia-app/gaia#701]
**Describe the bug**
Please can someone check this?  I'm assuming this is a bug since I'm following the instructions exactly.

I'm trying to start Gaia with the copy/paste docker-compose.yml example here: https://docs.gaia-app.io/getting-started/quick-start/

I get the following error from the 'runner' container on startup:
`
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in io.gaia_app.runner.StepRunner required a bean of type 'io.gaia_app.runner.Executor' that could not be found.

Action:

Consider defining a bean of type 'io.gaia_app.runner.Executor' in your configuration.
`

I used the docker-compose example exactly as-is

Thank you!

**To Reproduce**
Installed docker 20.10.7, docker-compose 1.29.2 on Debian stretch/sid

docker-compose.yml is copy/paste from the Gaia website:

```
version: "3.9"
services:
  gaia:
    image: "gaiaapp/gaia"
    ports:
      - "8080:8080"
    environment:
      - "GAIA_MONGODB_URI=mongodb://mongo/gaia"
      - "GAIA_RUNNER_API_PASSWORD=123456"
  runner:
    image: "gaiaapp/runner"
    environment:
      - "GAIA_URL=http://gaia:8080"
      - "GAIA_RUNNER_API_PASSWORD=123456"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  mongo:
    image: "mongo:4.4"
```

**Expected behavior**
The "runner" container should start, but it's not.
