### ISSUE TITLE
Connection refused on runner logs

### ISSUE THREAD

**Issue by jbrardport** [gaia-app/gaia#710]
I'm running locally using `docker-compose`

I'm using an m1 macbook.

Here is my file:

```yml
version: "3.9"
services:
  gaia:
    image: "gaiaapp/gaia"
    ports: 
      - "8080:8080"
    environment:
      - "GAIA_MONGODB_URI=mongodb://mongo/gaia"
      - "GAIA_RUNNER_API_PASSWORD=123456"
      - "GAIA_EXTERNAL_URL=http://127.0.0.1:8080"
  runner:
    image: "gaiaapp/runner"
    environment:
      - "GAIA_URL=http://127.0.0.1:8080"
      - "GAIA_RUNNER_API_PASSWORD=123456"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  mongo:
    image: "mongo:4.4"
```

I'm getting Plan Pending in the UI and the logs of the runner are:

```txt
Polling for pending steps
test-runner-1  | 2022-05-19 18:18:16.998 ERROR 1 --- [   scheduling-1] io.gaia_app.runner.StepPoller            : Unable to connect to gaia find jobs to run : I/O error on GET request for "http://127.0.0.1:8080/api/runner/steps/request": Connection refused; nested exception is java.net.ConnectException: Connection refused
```

Any advice?
