### ISSUE TITLE
🐛 : Problem with Runner

### ISSUE THREAD

**Issue by chwiee** [gaia-app/gaia#750]
**Describe the bug**
I create stack with Docker-Compose following doc, but when i try running any stack the runner show error:

Unable to connect to gaia find jobs to run : I/O error on GET request for "http://localhost:8080/api/runner/steps/request": Connection refused; nested exception is java.net.ConnectException: Connection refused

I try change the port, url but only error

**To Reproduce**
1. Running docker-compose up -d
2. Access with admin
3. Create a module or import from GitHub
4. Try Launch

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/8f1203d7-3f3f-4ac9-b3f3-e94f55b687b1)
![image](https://github.com/user-attachments/assets/c8bbc87e-e0b5-4164-bd95-cecd7550a05d)
![image](https://github.com/user-attachments/assets/5dd0a634-9515-4337-849d-c379767529f5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge and Chrome
 - Version Lkatest

**Comment by juwit** [comment]
Hey @barbaops  ! :wave: 

Can you share your docker-compose file?
The error `IO error on GET request for "http://localhost:8080/api/runner/steps/request"` means that your runner is missing the `GAIA_URL` configuration.

The related documentation is here: https://docs.gaia-app.io/getting-started/quick-start/#getting-started-with-docker-compose-pre-build-images

**Comment by chwiee** [comment]
Follow the docker-compose file:

```
version: "3.9"
services:
  gaia:
    image: "gaiaapp/gaia"
    ports: 
      - "8080:8080"
    environment:
      - "GAIA_MONGODB_URI=mongodb://mongo/gaia"
      - "GAIA_RUNNER_API_PASSWORD=123456"
      - "GAIA_EXTERNAL_URL=http://localhost:8080"
      - "SPRING_PROFILES_ACTIVE=github"
      - "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID=xxxxxxxxxx"
      - "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET=xxxxxxxxx"
  runner:
    image: "gaiaapp/runner"
    environment:
      - "GAIA_URL=http://localhost:8080"
      - "GAIA_RUNNER_API_PASSWORD=123456"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  mongo:
    image: "mongo:4.4"
```
    

I use docker in local machine

**Comment by juwit** [comment]
The problem is the GAIA_URL in the runner.

It should be `http://gaia:8080` (to use the gaia service)
The GAIA_EXTERNAL_URL in the gaia container can be `http://localhost:8080`.

So your docker-compose should be :

```
version: "3.9"
services:
  gaia:
    image: "gaiaapp/gaia"
    ports: 
      - "8080:8080"
    environment:
      - "GAIA_MONGODB_URI=mongodb://mongo/gaia"
      - "GAIA_RUNNER_API_PASSWORD=123456"
      - "GAIA_EXTERNAL_URL=http://localhost:8080"
      - "SPRING_PROFILES_ACTIVE=github"
      - "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID=xxxxxxxxxx"
      - "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET=xxxxxxxxx"
  runner:
    image: "gaiaapp/runner"
    environment:
      - "GAIA_URL=http://gaia:8080"
      - "GAIA_RUNNER_API_PASSWORD=123456"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  mongo:
    image: "mongo:4.4"
```

**Comment by chwiee** [comment]
Job stuck:

![image](https://github.com/user-attachments/assets/48fea535-a0c4-415a-9bd8-c4566cbdb3ef)


Gaia Log
![image](https://github.com/user-attachments/assets/111ded47-df7b-4de2-a279-078316e02939)


Runner Log:
![image](https://github.com/user-attachments/assets/f5aaab07-fbc2-4f9a-92fd-9f69ea8c93ca)



My compose file:
```
version: "3.9"
services:
  gaia:
    image: "gaiaapp/gaia"
    ports: 
      - "8080:8080"
    environment:
      - "GAIA_MONGODB_URI=mongodb://mongo/gaia"
      - "GAIA_RUNNER_API_PASSWORD=123456"
      - "GAIA_EXTERNAL_URL=http://localhost:8080"
      - "SPRING_PROFILES_ACTIVE=github"
      - "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID=xxxxxxxxxx"
      - "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET=xxxxxxxxx"
  runner:
    image: "gaiaapp/runner"
    environment:
      - "GAIA_URL=http://gaia:8080"
      - "GAIA_RUNNER_API_PASSWORD=123456"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  mongo:
    image: "mongo:4.4"
```
